# Generated by Django 3.2.7 on 2021-09-28 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dispositivos', '0001_initial'),
        ('Users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado',
            fields=[
                ('estado', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='fabricante',
            fields=[
                ('fabricante', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('pais', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='resultado',
            fields=[
                ('resultado', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('tipo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homologacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='homologacion/files')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(default='En curso', on_delete=django.db.models.deletion.CASCADE, to='Homologaciones.estado')),
                ('fabricante', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Homologaciones.fabricante')),
                ('id_dispositivo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Dispositivos.dispositivo')),
                ('pais', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Homologaciones.pais')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
                ('resultado', models.ForeignKey(default='Sin terminar', on_delete=django.db.models.deletion.CASCADE, to='Homologaciones.resultado')),
                ('tipo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Homologaciones.tipo')),
            ],
            options={
                'unique_together': {('refer', 'id_dispositivo', 'pais')},
            },
        ),
    ]
