# Generated by Django 3.2.7 on 2021-10-01 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profile_country'),
        ('Dispositivos', '0001_initial'),
        ('Homologaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homologacion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='homologacion',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='homologacion',
            name='id_dispositivo',
        ),
        migrations.RemoveField(
            model_name='homologacion',
            name='name',
        ),
        migrations.RemoveField(
            model_name='homologacion',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='homologacion',
            name='refer',
        ),
        migrations.CreateModel(
            name='referencia',
            fields=[
                ('id_referencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('refer', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fabricante', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Homologaciones.fabricante')),
                ('id_dispositivo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Dispositivos.dispositivo')),
                ('pais', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Homologaciones.pais')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
            ],
            options={
                'unique_together': {('refer', 'id_dispositivo', 'pais')},
            },
        ),
    ]
