# Generated by Django 3.2.7 on 2021-10-01 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homologaciones', '0002_auto_20211001_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='homologacion',
            name='refer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Homologaciones.referencia'),
        ),
    ]
