# Generated by Django 3.2.7 on 2021-10-13 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profile_country'),
        ('Dispositivos', '0002_alter_dispositivo_atributo_unique_together'),
        ('Homologaciones', '0003_homologacion_refer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homologacion',
            name='document',
        ),
        migrations.CreateModel(
            name='atributo_elemento_h',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=200)),
                ('document', models.FileField(upload_to='homologacion/files')),
                ('Homologacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homologaciones.homologacion')),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dispositivos.dispositivo_atributo')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
            ],
        ),
    ]
