# Generated by Django 3.2.8 on 2021-10-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homologaciones', '0004_auto_20211012_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributo_elemento_h',
            name='document',
            field=models.FileField(blank=True, upload_to='homologacion/files'),
        ),
    ]
