# Generated by Django 3.2.8 on 2021-10-26 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricantes', '0001_initial'),
        ('Homologaciones', '0005_alter_atributo_elemento_h_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='fabricante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Fabricantes.fabricante'),
        ),
        migrations.DeleteModel(
            name='fabricante',
        ),
    ]
