# Generated by Django 3.2.8 on 2021-10-26 05:56

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pais',
            fields=[
                ('pais', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='fabricante_pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representante', models.CharField(max_length=200)),
                ('numero', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fabricantes.fabricante')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fabricantes.pais')),
            ],
        ),
    ]
