# Generated by Django 3.2.8 on 2021-12-20 14:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricantes', '0002_fabricante_pais_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricante_pais',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fabricante_pais',
            name='numero',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='fabricante_pais',
            name='representante',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
