# Generated by Django 3.2.8 on 2021-12-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricantes', '0005_auto_20211220_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricante',
            name='capital',
        ),
        migrations.AddField(
            model_name='pais',
            name='capital',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
