# Generated by Django 3.2.8 on 2022-01-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricantes', '0006_auto_20211220_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='capital',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
