# Generated by Django 3.2.8 on 2021-10-28 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_profile_country'),
        ('Atributos', '0003_alter_atributo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atributo',
            name='User',
        ),
        migrations.AddField(
            model_name='atributo',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.profile'),
        ),
    ]
