# Generated by Django 3.2.7 on 2021-09-28 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '__first__'),
        ('Atributos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='dispositivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status_activo', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='dispositivo_atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atributos.atributo')),
                ('id_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dispositivos.dispositivo')),
            ],
        ),
    ]
