# Generated by Django 3.2.7 on 2021-10-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atributos', '0001_initial'),
        ('Dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dispositivo_atributo',
            unique_together={('id_dispositivo', 'id_atributo')},
        ),
    ]
