# Generated by Django 3.2.8 on 2021-10-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dispositivos', '0002_alter_dispositivo_atributo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
