# Generated by Django 3.2.8 on 2021-10-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dispositivos', '0003_alter_dispositivo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
